<?php

/**
 * @file
 * Generates image previews of PDF files.
 */

/**
 * Implements hook_theme().
 */
function pdfpreview_theme($existing, $type, $theme, $path) {
  return array(
    'pdfpreview_formatter' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Prepares variables for pdfpreview_formatter element templates.
 *
 * Default template: pdfpreview-formatter.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_pdfpreview_formatter(&$variables) {
  $settings = $variables['element']['#settings'];
  $variables['tag'] = $settings['tag'];
  $variables['fid'] = $variables['element']['#fid'];
  $variables['description'] = $settings['show_description'] ? $variables['element']['#description'] : '';
}
